Add NordVPN module to rofi

diff --git a/binaries/nordvpn/nordvpn b/binaries/nordvpn/nordvpn
--- a/binaries/nordvpn/nordvpn
+++ b/binaries/nordvpn/nordvpn
@@ -1,32 +1,44 @@
 #!/bin/sh
 
-CONFIG_FOLDER=~/.config/nordvpn
+CONFIG_FOLDER=$HOME/.config/nordvpn
+
+list_countries() {
+  ls $CONFIG_FOLDER/profiles/ovpn_udp/ | cut -c 1-2 | uniq
+}
 
 connect() {
   local country=$1
   local file
 
-  if [[ $(status) = "connected" ]]
+  if [[ $(is_vpn_connected) = "connected" ]]
   then
-    echo "OpenVPN is already running"
+    notify-send "OpenVPN is already running"
     exit 1
   fi
 
   if [[ -z $country ]]
   then
-    file=$(ls -1 $CONFIG_FOLDER/profiles/ovpn_udp/ | shuf -n 1)
+    file=$(ls -1 $CONFIG_FOLDER/profiles/ovpn_udp/* | shuf -n 1)
   else
     file=$(ls -1 $CONFIG_FOLDER/profiles/ovpn_udp/$country* | shuf -n 1)
   fi
 
-  # disable IPv6
-  sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null
-  sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 > /dev/null
+  notify-send -t 2000 "Waiting for connection"
 
-  echo "Connecting using config $file"
-  sudo daemonize -e nordvpn.log -o nordvpn.log $(which openvpn) --config $file --auth-user-pass $CONFIG_FOLDER/service-credentials
+  pkexec sh -c "sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && daemonize -e $HOME/nordvpn.log -o $HOME/nordvpn.log $(which openvpn) --config $file --auth-user-pass $CONFIG_FOLDER/service-credentials"
+  if [[ $? -ne 0 ]]
+  then
+    notify-send -u critical "Failed to connect"
+    return
+  fi
 
-  wait_for_status "connected"
+  local status=$(wait_for_status "connected")
+  if [[ $status = "done" ]]
+  then
+    notify-send "Connected to NordVPN"
+  else
+    notify-send -u critical "Failed to connect" "$(cat $HOME/nordvpn.log)"
+  fi
 
   rm -f nordvpn.log
 }
@@ -35,17 +47,19 @@ wait_for_status() {
   local counter=0
   local desired_status=$1
 
-  while [ ! "$(status)" = "$desired_status" ]; do
+  while [ ! "$(is_vpn_connected)" = "$desired_status" ]; do
     sleep 0.1
     counter=$((counter + 1))
     if [ $counter -ge 50 ]; then
-      echo "Waited for 5 seconds. Aborting connection"
-      exit 1
+      echo "error"
+      return
     fi
   done
+
+  echo "done"
 }
 
-status() {
+is_vpn_connected() {
   nmcli connection show tun0 >/dev/null 2>&1
   if [ $? -eq 0 ]; then
     echo "connected"
@@ -55,8 +69,14 @@ status() {
 }
 
 disconnect() {
-  sudo killall openvpn
-  wait_for_status "disconnected"
+  pkexec killall openvpn
+  local status=$(wait_for_status "disconnected")
+  if [[ $status = "done" ]]
+  then
+    notify-send "Disconnected from NordVPN"
+  else
+    notify-send -u critical "Failed to disconnect"
+  fi
 }
 
 update_configurations() {
@@ -73,6 +93,7 @@ usage() {
   echo "Manage NordVPN connections."
   echo ""
   echo "ACTION can be any of:"
+  echo " list: list countries with NordVPN servers"
   echo " connect: connects to a NordVPN"
   echo " disconnect: disconnects from NordVPN"
   echo " status: displays the NordVPN connection status"
@@ -102,7 +123,10 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-if [[ $ACTION = "connect" ]]
+if [[ $ACTION = "list-countries" ]]
+then
+  list_countries
+elif [[ $ACTION = "connect" ]]
 then
   connect $COUNTRY
 elif [[ $ACTION = "disconnect" ]]
@@ -110,7 +134,7 @@ then
   disconnect
 elif [[ $ACTION = "status" ]]
 then
-  status
+  is_vpn_connected
 elif [[ $ACTION = "update" ]]
 then
   update_configurations
